### ISSUE TITLE
Can not update plugin on PostgreSQL

### ISSUE THREAD

**Issue by juerghoerner** [markward/enrol_autoenrol#6] opened 2015-02-18 20:19 UTC
I think this error has something to do with the postgres DB. moodle 2.7

enrol_autoenrol
Fehler beim Lesen der Datenbank

Weitere Informationen über diesen Fehler

Debug info: ERROR: invalid input syntax for integer: ""
SELECT * FROM mdl_groups WHERE id = $1
[array (
0 => '',
)]
Error code: dmlreadexception
Stack trace:
line 443 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 244 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 764 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 1305 of /lib/dml/moodle_database.php: call to pgsql_native_moodle_database->get_records_sql()
line 1278 of /lib/dml/moodle_database.php: call to moodle_database->get_records_select()
line 48 of /enrol/autoenrol/db/upgrade.php: call to moodle_database->get_records_list()
line 535 of /lib/upgradelib.php: call to xmldb_enrol_autoenrol_upgrade()
line 1615 of /lib/upgradelib.php: call to upgrade_plugins()
line 434 of /admin/index.php: call to upgrade_noncore()

**Comment by markward** [comment] 2015-02-19 10:22
Hi Jürg,

It looks like the problem could be occurring before the DB query on line 48 of upgrade.php. Would it be possible for you to share an export of the following tables from your database?

* mdl_enrol
* mdl_group

This would be extremely helpful in trying to understand the problem.

Thanks

Mark

**Comment by juerghoerner** [comment] 2015-02-20 14:12
Hi Mark 

 

I made a print screen of both, is that what you want or would you the data in the tables as an export. 

 

Thank you for your help. 

 

With FTP I set the auto enrol to  0000. Than I can make the db update with no error. 

 

It is also not possible to delete a course witch had autoenrol, because of that problem I updated the auto_enrole.

 

Jürg 

 

A similar error I found here: 

https://tracker.moodle.org/browse/MDL-26587 

 

Von: Mark Ward [mailto:notifications@github.com] 
Gesendet: Donnerstag, 19. Februar 2015 11:23
An: markward/enrol_autoenrol
Cc: juerghoerner
Betreff: Re: [enrol_autoenrol] error: can not update autoenrol (#6)

 

Hi Jürg,

It looks like the problem could be occurring before the DB query on line 48 of upgrade.php. Would it be possible for you to share an export of the following tables from your database?

*	mdl_enrol
*	mdl_group

This would be extremely helpful in trying to understand the problem.

Thanks

Mark

**Comment by markward** [comment] 2015-02-20 15:00
Hi Jürg

I can probably work from screenshots, however you'll need to drag and drop them into a reply on the GitHub site itself as it doesn't seem to have picked them up from your email.

When you say you "set the auto enrol to 0000" with FTP, could you explain that in a little more detail for me? are you editing a PHP script or modifying data in your database?

Thanks

Mark

**Comment by juerghoerner** [comment] 2015-02-20 15:24
Hi Mark 
1. set auto enrol to 0000 means the rights of the folder, if it set to 2775 I cant work as admin. That moodle can not acces autoenrol. No changes in php code or the database. 
2. Pictures are attached. 
![mdl_enrol 3](https://cloud.githubusercontent.com/assets/8375663/6288868/47180d3c-b91c-11e4-8328-8ab9c4af374a.jpg)
![mdl_groups](https://cloud.githubusercontent.com/assets/8375663/6288869/471b280a-b91c-11e4-9f25-da5e4d5f98d9.jpg)

My IT Supporter from school made an export off both tales. I will send them by email. 

kind regards 
Jürg

**Comment by juerghoerner** [comment] 2015-02-20 15:40
Hi Mark 

 

I send you the sql exports. 

 

I will look, if I have the old plugin with the VersionNr

2013070100  

 

Maybe we have to wait until I install a newer version of moodle. 

Did you test it with version 2.8.x? 

Should I reorganise the postgres db? 

 

http://stackoverflow.com/questions/15637944/invalid-input-syntax-for-integer-when-submitting-form 

 

I am the moodle admin as a teacher at school. 

 

Thanks 

Jürg 

 

Von: Mark Ward [mailto:notifications@github.com] 
Gesendet: Freitag, 20. Februar 2015 16:00
An: markward/enrol_autoenrol
Cc: juerghoerner
Betreff: Re: [enrol_autoenrol] Can not update plugin on PostgreSQL (#6)

 

Hi Jürg

I can probably work from screenshots, however you'll need to drag and drop them into a reply on the GitHub site itself as it doesn't seem to have picked them up from your email.

When you say you "set the auto enrol to 0000" with FTP, could you explain that in a little more detail for me? are you editing a PHP script or modifying data in your database?

Thanks

Mark

**Comment by markward** [comment] 2015-02-20 16:36
Hi Jürg

Definitely don't make any modifications to the database. I'd also suggest not modifying the permissions on those files since it's almost certainly not the cause of the problem. 

I've just pushed commit 4800ef3 (and 9bc16b7) which will hopefully resolve this problem for you. You should be fine to just take a copy of enrol/autoenrol/db/upgrade.php and overwrite your copy with it.

The change ensures that there is no possibility of the database being fed a non-integer at that point, so if the problem persists we know it's something else.

Fingers crossed!

Mark

**Comment by markward** [comment] 2015-02-21 12:26
Hi Jürg

Glad to hear that fixed it! I'll close this off.

The caching error might be caused by bad file permissions. Best bet would be to try purging caches and then resetting the file permissions to something that allows Apache to read and write those files.

Thanks

Mark

**Closed** 2015-02-21 12:26 UTC
Labels: bug
